---
version: '3.7'

services:

    nginx:
      image: nginx:latest
      volumes:
      - type: bind
        source: /var/jenkins_home/workspace/quad-base/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - client
        - server

    server:
      image: 127.0.0.1:5000/server:2
      build:
        context: ./server
        dockerfile: Dockerfile
      depends_on:
        - mongo

    client:
      image: 127.0.0.1:5000/client:2
      build:
        context: ./client
        dockerfile: Dockerfile
      environment:
      - REACT_APP_SERVICE_HOST=${REACT_APP_SERVICE_HOST}
      depends_on:
        - server

    mongo:
      image: mongo:latest

    mongo-seed:
      image: fvilers/mongo-seed:1.0.0
      environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      volumes:
      - ./data:/data
      command:
      - "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/account.json --jsonArray"
      restart: on-failure
  
...

